export enum Categoria {

  ALIMENTACAO = "ALIMENTACAO",
  SAUDE = "SAUDE",
  MORADIA = "MORADIA",
  TRANSPORTE = "TRANSPORTE",
  EDUCACAO = "EDUCACAO",
  LAZER = "LAZER",
  IMPREVISTOS = "IMPREVISTOS",
  OUTRAS = "OUTRAS"
}
